# Generated by Django 4.0 on 2021-12-25 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersInf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('phone_number', models.CharField(max_length=150, null=True, verbose_name='Номер телефона')),
                ('code', models.IntegerField(verbose_name='Код активации')),
                ('surname', models.CharField(max_length=150, null=True, verbose_name='Фамилия')),
                ('name', models.CharField(max_length=150, null=True, verbose_name='Имя')),
                ('patronymic', models.CharField(max_length=150, null=True, verbose_name='Отчество')),
                ('role', models.CharField(choices=[('Entrant', 'Абитуриент'), ('Company', 'Компания')], default='Entrant', max_length=30, verbose_name='Статуc')),
                ('user', models.OneToOneField(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='Связь с таблицей пользователей')),
            ],
        ),
    ]
