# Generated by Django 4.0 on 2021-12-31 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main_app', '0003_usersinf_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersinf',
            name='patronymic',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='usersinf',
            name='surname',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='usersinf',
            name='user',
            field=models.OneToOneField(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_info', to='auth.user', verbose_name='Связь с таблицей пользователей'),
        ),
    ]
