# Generated by Django 4.0 on 2022-01-04 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main_app', '0004_alter_usersinf_patronymic_alter_usersinf_surname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partners', models.TextField(default='', null=True, verbose_name='Список Партнеров')),
                ('description', models.TextField(default='', verbose_name='Описание вакансии')),
                ('requirements', models.TextField(default='', verbose_name='Требования к соискателю')),
                ('organisation', models.OneToOneField(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organisation', to='auth.user', verbose_name='Связь с таблицей пользователей')),
            ],
        ),
    ]
