# Generated by Django 4.0 on 2022-01-05 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main_app', '0006_vacancy_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='organisation',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organisation', to='auth.user', verbose_name='Связь с таблицей пользователей'),
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='partners',
            field=models.TextField(default='', null=True, verbose_name='Список вузов партнеров'),
        ),
    ]
