# Generated by Django 4.0 on 2022-01-08 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main_app', '0007_alter_vacancy_organisation_alter_vacancy_partners'),
    ]

    operations = [
        migrations.CreateModel(
            name='Responses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='Связь с таблицей пользователей')),
                ('vacancy', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vacancy', to='main_app.vacancy', verbose_name='Связь с таблицей вакансии')),
            ],
        ),
    ]
