# Generated by Django 4.0 on 2022-01-21 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main_app', '0008_responses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responses',
            name='user',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user', verbose_name='Связь с таблицей пользователей'),
        ),
    ]
