# Generated by Django 4.0 on 2022-01-25 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_responses_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Название специальности')),
                ('code', models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Код специальности')),
            ],
        ),
        migrations.CreateModel(
            name='Universities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Название вуза')),
            ],
        ),
    ]
