# Generated by Django 4.0 on 2022-01-25 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_direction_universities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersinf',
            name='role',
            field=models.CharField(choices=[('Entrant', 'Абитуриент'), ('Company', 'Компания'), ('Admin', 'Админ')], default='Entrant', max_length=30, verbose_name='Статуc'),
        ),
    ]
