# Generated by Django 4.0 on 2022-01-31 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_alter_usersinf_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyRegApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True, verbose_name='Имя')),
                ('email', models.CharField(max_length=250, null=True, verbose_name='Email')),
                ('phone_number', models.CharField(max_length=150, null=True, verbose_name='Номер телефона')),
                ('text_about', models.TextField(default='', verbose_name='Текст о пользователе')),
            ],
        ),
        migrations.AlterField(
            model_name='usersinf',
            name='name',
            field=models.CharField(max_length=250, null=True, verbose_name='Имя'),
        ),
    ]
