# Generated by Django 4.0 on 2022-02-10 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_companyregapplication_alter_usersinf_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='is_frozen',
            field=models.BooleanField(default=False, verbose_name='Заморожено?'),
        ),
    ]
